# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         eBay-API
version_from: lib/eBay/API.pm
installdirs:  site
requires:
    Compress::Zlib:                1.41
    Crypt::SSLeay:                 0.51
    Cwd:                           3.18
    Data::Dumper:                  2.121
    Devel::StackTrace:             1.03
    Encode:                        1.9801
    Error:                         0.15
    Exception::Class:              1.14
    Exporter:                      5.567
    File::Find:                    1.05
    File::Path:                    1.06
    File::Spec:                    3.18
    Getopt::Long:                  2.34
    HTTP::Headers:                 1.47
    HTTP::Request:                 1.34
    HTTP::Status:                  1.28
    IO::File:                      1.1
    LWP::Parallel:                 2.57
    LWP::UserAgent:                2.023
    Params::Validate:              0.74
    Scalar::Util:                  1.11
    Time::HiRes:                   1.51
    Time::localtime:               1.02
    XML::Simple:                   2.09
    XML::Tidy:                     1.2.54HJnFa
    XML::Writer:                   0.6
no_index:
    directory:
        - lib/eBay/API/XML/tools
distribution_type: module
